config bsg_config;
  design `BSG_DESIGNS_TESTING_LIBRARY_NAME.`BSG_TOP_SIM_MODULE;
  default liblist `BSG_DESIGNS_TESTING_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME work;

  // Swaplist is a list of instances to swap for ***netlists***. In this TB
  // it swaps out quadrapod 0, and enumerates the top qudrapod
  // (bsg_manycore_pod_row_sdr), all 16x2 tile arrays within the pods,
  // all tiles within the tile arrays, all north and south cache
  // arrays within the pods, and all caches within the cache arrays.

  // Swaplist.vh is generated by the makefile.
  `include "swaplist.vh"

  // Swap these for netlists, universally.
  cell bigblade_clk_gen liblist `BIGBLADE_CLK_GEN_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_chip_io_link_ddr liblist `BIGBLADE_IO_LINK_DDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_chip_noc_io_link liblist `BIGBLADE_NOC_IO_LINK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_chip_noc_mem_link liblist `BIGBLADE_NOC_MEM_LINK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_tiehi liblist `BSG_TIEHILO_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_tielo liblist `BSG_TIEHILO_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_chip_block liblist `BIGBLADE_TOPLEVEL_BLOCK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;  
  cell bsg_chip liblist `BIGBLADE_TOPLEVEL_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;  

  // Swap these for RTL hard (if they are not enumerated above -- this is the "else" clause)
  cell bsg_manycore_tile_compute_ruche liblist `BSG_MANYCORE_TILE_HARD_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_tile_vcache liblist `BSG_MANYCORE_TILE_HARD_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // These do not have hardened modules inside of them. OK to leave
  // as-is. If they DO have hardened modules then they will need to be
  // uncommented and a module-specific "XXX_HARD_LIBRARY" will need to
  // be created. Any instances that need netlists will need to be
  // netlists (instead of RTL Hard) should be in swaplists.vh

  // cell bsg_manycore_tile_compute_array_ruche liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_tile_vcache_array liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_pod_row_sdr liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // cell bsg_manycore_link_ruche_to_sdr_east liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_link_ruche_to_sdr_west liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // cell bsg_manycore_link_to_sdr_north liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_link_to_sdr_north_row liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // cell bsg_manycore_link_to_sdr_south liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_link_to_sdr_south_row liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // cell bsg_manycore_link_wh_to_sdr_ne liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_link_wh_to_sdr_nw liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_link_wh_to_sdr_se liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  // cell bsg_manycore_link_wh_to_sdr_sw liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

endconfig
