
export_build:
	python3 `git rev-parse --show-toplevel`/common/exporter/export_build.py bsg_14/current_build 2>&1 | tee -i $@.log

export_netlist_post_synth:
	python3 `git rev-parse --show-toplevel`/common/exporter/export_build.py bsg_14/current_build --netlist-post-synth 2>&1 | tee -i $@.log

export_netlist_post_apr:
	python3 `git rev-parse --show-toplevel`/common/exporter/export_build.py bsg_14/current_build --netlist-post-apr 2>&1 | tee -i $@.log

