genvar i;

`ifndef BSG_PAD_INPUT_PULLDOWN
BSG_PAD_INPUT_PULLDOWN should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_A
BSG_PAD_OUTPUT_A should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_B
BSG_PAD_OUTPUT_B should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_C
BSG_PAD_OUTPUT_C should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_D
BSG_PAD_OUTPUT_D should be defined!
`endif

`ifndef BSG_PAD_OUTPUT_SLOW
BSG_PAD_OUTPUT_SLOW should be defined!
`endif

`ifndef BSG_PAD_DISABLE
BSG_PAD_DISABLE should be defined!
`endif

`ifndef BSG_PAD_INOUT
BSG_PAD_INOUT should be defined!
`endif

  `BSG_IO_IN   (bsg_link_in0_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in0_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in0_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in0_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in0_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in1_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in1_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in1_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in1_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in1_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in2_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in2_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in2_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in2_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in2_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in3_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in3_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in3_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in3_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in3_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in4_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in4_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in4_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in4_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in4_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in5_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in5_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in5_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in5_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in5_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in6_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in6_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in6_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in6_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in6_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in7_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in7_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in7_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in7_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in7_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in8_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in8_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in8_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in8_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in8_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in9_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in9_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in9_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in9_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in9_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in10_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in10_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in10_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in10_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in10_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in11_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in11_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in11_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in11_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in11_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in12_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in12_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in12_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in12_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in12_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in13_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in13_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in13_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in13_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in13_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in14_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in14_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in14_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in14_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in14_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in15_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in15_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in15_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in15_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in15_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in16_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in16_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in16_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in16_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in16_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in17_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in17_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in17_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in17_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in17_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in18_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in18_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in18_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in18_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in18_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (bsg_link_in19_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_v,    `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_in19_tkn,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_in19_tkn_oen_int)
  `BSG_IO_IN   (bsg_link_in19_d0,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d1,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d2,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d3,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d4,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d5,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d6,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d7,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_link_in19_d8,   `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_OUT  (bsg_link_out0_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_v_oen_int)
  `BSG_IO_IN   (bsg_link_out0_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out0_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out0_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out0_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out1_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_v_oen_int)
  `BSG_IO_IN   (bsg_link_out1_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out1_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out1_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out1_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out2_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_v_oen_int)
  `BSG_IO_IN   (bsg_link_out2_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out2_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out2_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out2_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out3_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_v_oen_int)
  `BSG_IO_IN   (bsg_link_out3_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out3_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out3_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out3_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out4_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_v_oen_int)
  `BSG_IO_IN   (bsg_link_out4_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out4_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out4_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out4_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out5_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_v_oen_int)
  `BSG_IO_IN   (bsg_link_out5_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out5_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out5_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out5_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out6_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_v_oen_int)
  `BSG_IO_IN   (bsg_link_out6_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out6_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out6_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out6_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out7_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_v_oen_int)
  `BSG_IO_IN   (bsg_link_out7_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out7_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out7_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out7_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out8_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_v_oen_int)
  `BSG_IO_IN   (bsg_link_out8_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out8_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out8_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out8_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out9_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_v_oen_int)
  `BSG_IO_IN   (bsg_link_out9_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out9_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out9_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out9_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out10_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_v_oen_int)
  `BSG_IO_IN   (bsg_link_out10_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out10_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out10_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out10_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out11_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_v_oen_int)
  `BSG_IO_IN   (bsg_link_out11_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out11_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out11_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out11_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out12_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_v_oen_int)
  `BSG_IO_IN   (bsg_link_out12_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out12_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out12_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out12_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out13_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_v_oen_int)
  `BSG_IO_IN   (bsg_link_out13_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out13_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out13_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out13_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out14_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_v_oen_int)
  `BSG_IO_IN   (bsg_link_out14_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out14_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out14_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out14_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out15_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_v_oen_int)
  `BSG_IO_IN   (bsg_link_out15_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out15_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out15_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out15_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out16_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_v_oen_int)
  `BSG_IO_IN   (bsg_link_out16_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out16_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out16_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out16_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out17_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_v_oen_int)
  `BSG_IO_IN   (bsg_link_out17_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out17_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out17_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out17_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out18_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_v_oen_int)
  `BSG_IO_IN   (bsg_link_out18_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out18_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out18_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out18_d8_oen_int)

  `BSG_IO_OUT  (bsg_link_out19_clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_clk_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_v,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_v_oen_int)
  `BSG_IO_IN   (bsg_link_out19_tkn, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_link_out19_d0,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d0_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d1,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d1_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d2,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d2_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d3,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d3_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d4,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d4_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d5,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d5_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d6,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d6_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d7,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d7_oen_int)
  `BSG_IO_OUT  (bsg_link_out19_d8,   `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_link_out19_d8_oen_int)

  `BSG_IO_IN   (bsg_tag_clk,  `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_tag_en,   `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (bsg_tag_data, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_OUT  (bsg_tag_clk,  `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_tag_clk_oen_int)
  `BSG_IO_OUT  (bsg_tag_data, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(bsg_tag_data_oen_int)

  `BSG_IO_IN   (clk_A, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (clk_B, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (clk_C, `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_OUT  (clk, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(clk_oen_int)

  `BSG_IO_IN   (sel_0, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (sel_1, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (sel_2, `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_IN   (clk_async_reset, `BSG_PAD_INPUT_PULLDOWN)
  `BSG_IO_IN   (core_async_reset, `BSG_PAD_INPUT_PULLDOWN)

  `BSG_IO_OUT  (misc, `BSG_PAD_OUTPUT_SLOW)
  `BSG_IO_TIELO(misc_oen_int)
