
  (
  // 20 full-duplex bsg_link interfaces, 480 pins
  // Output links
  ,output p_bsg_link_in0_clk_o
  ,output p_bsg_link_in0_v_o
  ,input  p_bsg_link_in0_tkn_i
  ,output p_bsg_link_in0_d0_o
  ,output p_bsg_link_in0_d1_o
  ,output p_bsg_link_in0_d2_o
  ,output p_bsg_link_in0_d3_o
  ,output p_bsg_link_in0_d4_o
  ,output p_bsg_link_in0_d5_o
  ,output p_bsg_link_in0_d6_o
  ,output p_bsg_link_in0_d7_o
  ,output p_bsg_link_in0_d8_o

  ,output p_bsg_link_in1_clk_o
  ,output p_bsg_link_in1_v_o
  ,input  p_bsg_link_in1_tkn_i
  ,output p_bsg_link_in1_d0_o
  ,output p_bsg_link_in1_d1_o
  ,output p_bsg_link_in1_d2_o
  ,output p_bsg_link_in1_d3_o
  ,output p_bsg_link_in1_d4_o
  ,output p_bsg_link_in1_d5_o
  ,output p_bsg_link_in1_d6_o
  ,output p_bsg_link_in1_d7_o
  ,output p_bsg_link_in1_d8_o

  ,output p_bsg_link_in2_clk_o
  ,output p_bsg_link_in2_v_o
  ,input  p_bsg_link_in2_tkn_i
  ,output p_bsg_link_in2_d0_o
  ,output p_bsg_link_in2_d1_o
  ,output p_bsg_link_in2_d2_o
  ,output p_bsg_link_in2_d3_o
  ,output p_bsg_link_in2_d4_o
  ,output p_bsg_link_in2_d5_o
  ,output p_bsg_link_in2_d6_o
  ,output p_bsg_link_in2_d7_o
  ,output p_bsg_link_in2_d8_o

  ,output p_bsg_link_in3_clk_o
  ,output p_bsg_link_in3_v_o
  ,input  p_bsg_link_in3_tkn_i
  ,output p_bsg_link_in3_d0_o
  ,output p_bsg_link_in3_d1_o
  ,output p_bsg_link_in3_d2_o
  ,output p_bsg_link_in3_d3_o
  ,output p_bsg_link_in3_d4_o
  ,output p_bsg_link_in3_d5_o
  ,output p_bsg_link_in3_d6_o
  ,output p_bsg_link_in3_d7_o
  ,output p_bsg_link_in3_d8_o

  ,output p_bsg_link_in4_clk_o
  ,output p_bsg_link_in4_v_o
  ,input  p_bsg_link_in4_tkn_i
  ,output p_bsg_link_in4_d0_o
  ,output p_bsg_link_in4_d1_o
  ,output p_bsg_link_in4_d2_o
  ,output p_bsg_link_in4_d3_o
  ,output p_bsg_link_in4_d4_o
  ,output p_bsg_link_in4_d5_o
  ,output p_bsg_link_in4_d6_o
  ,output p_bsg_link_in4_d7_o
  ,output p_bsg_link_in4_d8_o

  ,output p_bsg_link_in5_clk_o
  ,output p_bsg_link_in5_v_o
  ,input  p_bsg_link_in5_tkn_i
  ,output p_bsg_link_in5_d0_o
  ,output p_bsg_link_in5_d1_o
  ,output p_bsg_link_in5_d2_o
  ,output p_bsg_link_in5_d3_o
  ,output p_bsg_link_in5_d4_o
  ,output p_bsg_link_in5_d5_o
  ,output p_bsg_link_in5_d6_o
  ,output p_bsg_link_in5_d7_o
  ,output p_bsg_link_in5_d8_o

  ,output p_bsg_link_in6_clk_o
  ,output p_bsg_link_in6_v_o
  ,input  p_bsg_link_in6_tkn_i
  ,output p_bsg_link_in6_d0_o
  ,output p_bsg_link_in6_d1_o
  ,output p_bsg_link_in6_d2_o
  ,output p_bsg_link_in6_d3_o
  ,output p_bsg_link_in6_d4_o
  ,output p_bsg_link_in6_d5_o
  ,output p_bsg_link_in6_d6_o
  ,output p_bsg_link_in6_d7_o
  ,output p_bsg_link_in6_d8_o

  ,output p_bsg_link_in7_clk_o
  ,output p_bsg_link_in7_v_o
  ,input  p_bsg_link_in7_tkn_i
  ,output p_bsg_link_in7_d0_o
  ,output p_bsg_link_in7_d1_o
  ,output p_bsg_link_in7_d2_o
  ,output p_bsg_link_in7_d3_o
  ,output p_bsg_link_in7_d4_o
  ,output p_bsg_link_in7_d5_o
  ,output p_bsg_link_in7_d6_o
  ,output p_bsg_link_in7_d7_o
  ,output p_bsg_link_in7_d8_o

  ,output p_bsg_link_in8_clk_o
  ,output p_bsg_link_in8_v_o
  ,input  p_bsg_link_in8_tkn_i
  ,output p_bsg_link_in8_d0_o
  ,output p_bsg_link_in8_d1_o
  ,output p_bsg_link_in8_d2_o
  ,output p_bsg_link_in8_d3_o
  ,output p_bsg_link_in8_d4_o
  ,output p_bsg_link_in8_d5_o
  ,output p_bsg_link_in8_d6_o
  ,output p_bsg_link_in8_d7_o
  ,output p_bsg_link_in8_d8_o

  ,output p_bsg_link_in9_clk_o
  ,output p_bsg_link_in9_v_o
  ,input  p_bsg_link_in9_tkn_i
  ,output p_bsg_link_in9_d0_o
  ,output p_bsg_link_in9_d1_o
  ,output p_bsg_link_in9_d2_o
  ,output p_bsg_link_in9_d3_o
  ,output p_bsg_link_in9_d4_o
  ,output p_bsg_link_in9_d5_o
  ,output p_bsg_link_in9_d6_o
  ,output p_bsg_link_in9_d7_o
  ,output p_bsg_link_in9_d8_o

  ,output p_bsg_link_in10_clk_o
  ,output p_bsg_link_in10_v_o
  ,input  p_bsg_link_in10_tkn_i
  ,output p_bsg_link_in10_d0_o
  ,output p_bsg_link_in10_d1_o
  ,output p_bsg_link_in10_d2_o
  ,output p_bsg_link_in10_d3_o
  ,output p_bsg_link_in10_d4_o
  ,output p_bsg_link_in10_d5_o
  ,output p_bsg_link_in10_d6_o
  ,output p_bsg_link_in10_d7_o
  ,output p_bsg_link_in10_d8_o

  ,output p_bsg_link_in11_clk_o
  ,output p_bsg_link_in11_v_o
  ,input  p_bsg_link_in11_tkn_i
  ,output p_bsg_link_in11_d0_o
  ,output p_bsg_link_in11_d1_o
  ,output p_bsg_link_in11_d2_o
  ,output p_bsg_link_in11_d3_o
  ,output p_bsg_link_in11_d4_o
  ,output p_bsg_link_in11_d5_o
  ,output p_bsg_link_in11_d6_o
  ,output p_bsg_link_in11_d7_o
  ,output p_bsg_link_in11_d8_o

  ,output p_bsg_link_in12_clk_o
  ,output p_bsg_link_in12_v_o
  ,input  p_bsg_link_in12_tkn_i
  ,output p_bsg_link_in12_d0_o
  ,output p_bsg_link_in12_d1_o
  ,output p_bsg_link_in12_d2_o
  ,output p_bsg_link_in12_d3_o
  ,output p_bsg_link_in12_d4_o
  ,output p_bsg_link_in12_d5_o
  ,output p_bsg_link_in12_d6_o
  ,output p_bsg_link_in12_d7_o
  ,output p_bsg_link_in12_d8_o

  ,output p_bsg_link_in13_clk_o
  ,output p_bsg_link_in13_v_o
  ,input  p_bsg_link_in13_tkn_i
  ,output p_bsg_link_in13_d0_o
  ,output p_bsg_link_in13_d1_o
  ,output p_bsg_link_in13_d2_o
  ,output p_bsg_link_in13_d3_o
  ,output p_bsg_link_in13_d4_o
  ,output p_bsg_link_in13_d5_o
  ,output p_bsg_link_in13_d6_o
  ,output p_bsg_link_in13_d7_o
  ,output p_bsg_link_in13_d8_o

  ,output p_bsg_link_in14_clk_o
  ,output p_bsg_link_in14_v_o
  ,input  p_bsg_link_in14_tkn_i
  ,output p_bsg_link_in14_d0_o
  ,output p_bsg_link_in14_d1_o
  ,output p_bsg_link_in14_d2_o
  ,output p_bsg_link_in14_d3_o
  ,output p_bsg_link_in14_d4_o
  ,output p_bsg_link_in14_d5_o
  ,output p_bsg_link_in14_d6_o
  ,output p_bsg_link_in14_d7_o
  ,output p_bsg_link_in14_d8_o

  ,output p_bsg_link_in15_clk_o
  ,output p_bsg_link_in15_v_o
  ,input  p_bsg_link_in15_tkn_i
  ,output p_bsg_link_in15_d0_o
  ,output p_bsg_link_in15_d1_o
  ,output p_bsg_link_in15_d2_o
  ,output p_bsg_link_in15_d3_o
  ,output p_bsg_link_in15_d4_o
  ,output p_bsg_link_in15_d5_o
  ,output p_bsg_link_in15_d6_o
  ,output p_bsg_link_in15_d7_o
  ,output p_bsg_link_in15_d8_o

  ,output p_bsg_link_in16_clk_o
  ,output p_bsg_link_in16_v_o
  ,input  p_bsg_link_in16_tkn_i
  ,output p_bsg_link_in16_d0_o
  ,output p_bsg_link_in16_d1_o
  ,output p_bsg_link_in16_d2_o
  ,output p_bsg_link_in16_d3_o
  ,output p_bsg_link_in16_d4_o
  ,output p_bsg_link_in16_d5_o
  ,output p_bsg_link_in16_d6_o
  ,output p_bsg_link_in16_d7_o
  ,output p_bsg_link_in16_d8_o

  ,output p_bsg_link_in17_clk_o
  ,output p_bsg_link_in17_v_o
  ,input  p_bsg_link_in17_tkn_i
  ,output p_bsg_link_in17_d0_o
  ,output p_bsg_link_in17_d1_o
  ,output p_bsg_link_in17_d2_o
  ,output p_bsg_link_in17_d3_o
  ,output p_bsg_link_in17_d4_o
  ,output p_bsg_link_in17_d5_o
  ,output p_bsg_link_in17_d6_o
  ,output p_bsg_link_in17_d7_o
  ,output p_bsg_link_in17_d8_o

  ,output p_bsg_link_in18_clk_o
  ,output p_bsg_link_in18_v_o
  ,input  p_bsg_link_in18_tkn_i
  ,output p_bsg_link_in18_d0_o
  ,output p_bsg_link_in18_d1_o
  ,output p_bsg_link_in18_d2_o
  ,output p_bsg_link_in18_d3_o
  ,output p_bsg_link_in18_d4_o
  ,output p_bsg_link_in18_d5_o
  ,output p_bsg_link_in18_d6_o
  ,output p_bsg_link_in18_d7_o
  ,output p_bsg_link_in18_d8_o

  ,output p_bsg_link_in19_clk_o
  ,output p_bsg_link_in19_v_o
  ,input  p_bsg_link_in19_tkn_i
  ,output p_bsg_link_in19_d0_o
  ,output p_bsg_link_in19_d1_o
  ,output p_bsg_link_in19_d2_o
  ,output p_bsg_link_in19_d3_o
  ,output p_bsg_link_in19_d4_o
  ,output p_bsg_link_in19_d5_o
  ,output p_bsg_link_in19_d6_o
  ,output p_bsg_link_in19_d7_o
  ,output p_bsg_link_in19_d8_o

  // Input links
   input  p_bsg_link_out0_clk_i
  ,input  p_bsg_link_out0_v_i
  ,output p_bsg_link_out0_tkn_o
  ,input  p_bsg_link_out0_d0_i
  ,input  p_bsg_link_out0_d1_i
  ,input  p_bsg_link_out0_d2_i
  ,input  p_bsg_link_out0_d3_i
  ,input  p_bsg_link_out0_d4_i
  ,input  p_bsg_link_out0_d5_i
  ,input  p_bsg_link_out0_d6_i
  ,input  p_bsg_link_out0_d7_i
  ,input  p_bsg_link_out0_d8_i
  
  ,input  p_bsg_link_out1_clk_i
  ,input  p_bsg_link_out1_v_i
  ,output p_bsg_link_out1_tkn_o
  ,input  p_bsg_link_out1_d0_i
  ,input  p_bsg_link_out1_d1_i
  ,input  p_bsg_link_out1_d2_i
  ,input  p_bsg_link_out1_d3_i
  ,input  p_bsg_link_out1_d4_i
  ,input  p_bsg_link_out1_d5_i
  ,input  p_bsg_link_out1_d6_i
  ,input  p_bsg_link_out1_d7_i
  ,input  p_bsg_link_out1_d8_i
  
  ,input  p_bsg_link_out2_clk_i
  ,input  p_bsg_link_out2_v_i
  ,output p_bsg_link_out2_tkn_o
  ,input  p_bsg_link_out2_d0_i
  ,input  p_bsg_link_out2_d1_i
  ,input  p_bsg_link_out2_d2_i
  ,input  p_bsg_link_out2_d3_i
  ,input  p_bsg_link_out2_d4_i
  ,input  p_bsg_link_out2_d5_i
  ,input  p_bsg_link_out2_d6_i
  ,input  p_bsg_link_out2_d7_i
  ,input  p_bsg_link_out2_d8_i
  
  ,input  p_bsg_link_out3_clk_i
  ,input  p_bsg_link_out3_v_i
  ,output p_bsg_link_out3_tkn_o
  ,input  p_bsg_link_out3_d0_i
  ,input  p_bsg_link_out3_d1_i
  ,input  p_bsg_link_out3_d2_i
  ,input  p_bsg_link_out3_d3_i
  ,input  p_bsg_link_out3_d4_i
  ,input  p_bsg_link_out3_d5_i
  ,input  p_bsg_link_out3_d6_i
  ,input  p_bsg_link_out3_d7_i
  ,input  p_bsg_link_out3_d8_i
  
  ,input  p_bsg_link_out4_clk_i
  ,input  p_bsg_link_out4_v_i
  ,output p_bsg_link_out4_tkn_o
  ,input  p_bsg_link_out4_d0_i
  ,input  p_bsg_link_out4_d1_i
  ,input  p_bsg_link_out4_d2_i
  ,input  p_bsg_link_out4_d3_i
  ,input  p_bsg_link_out4_d4_i
  ,input  p_bsg_link_out4_d5_i
  ,input  p_bsg_link_out4_d6_i
  ,input  p_bsg_link_out4_d7_i
  ,input  p_bsg_link_out4_d8_i
  
  ,input  p_bsg_link_out5_clk_i
  ,input  p_bsg_link_out5_v_i
  ,output p_bsg_link_out5_tkn_o
  ,input  p_bsg_link_out5_d0_i
  ,input  p_bsg_link_out5_d1_i
  ,input  p_bsg_link_out5_d2_i
  ,input  p_bsg_link_out5_d3_i
  ,input  p_bsg_link_out5_d4_i
  ,input  p_bsg_link_out5_d5_i
  ,input  p_bsg_link_out5_d6_i
  ,input  p_bsg_link_out5_d7_i
  ,input  p_bsg_link_out5_d8_i
  
  ,input  p_bsg_link_out6_clk_i
  ,input  p_bsg_link_out6_v_i
  ,output p_bsg_link_out6_tkn_o
  ,input  p_bsg_link_out6_d0_i
  ,input  p_bsg_link_out6_d1_i
  ,input  p_bsg_link_out6_d2_i
  ,input  p_bsg_link_out6_d3_i
  ,input  p_bsg_link_out6_d4_i
  ,input  p_bsg_link_out6_d5_i
  ,input  p_bsg_link_out6_d6_i
  ,input  p_bsg_link_out6_d7_i
  ,input  p_bsg_link_out6_d8_i
  
  ,input  p_bsg_link_out7_clk_i
  ,input  p_bsg_link_out7_v_i
  ,output p_bsg_link_out7_tkn_o
  ,input  p_bsg_link_out7_d0_i
  ,input  p_bsg_link_out7_d1_i
  ,input  p_bsg_link_out7_d2_i
  ,input  p_bsg_link_out7_d3_i
  ,input  p_bsg_link_out7_d4_i
  ,input  p_bsg_link_out7_d5_i
  ,input  p_bsg_link_out7_d6_i
  ,input  p_bsg_link_out7_d7_i
  ,input  p_bsg_link_out7_d8_i
  
  ,input  p_bsg_link_out8_clk_i
  ,input  p_bsg_link_out8_v_i
  ,output p_bsg_link_out8_tkn_o
  ,input  p_bsg_link_out8_d0_i
  ,input  p_bsg_link_out8_d1_i
  ,input  p_bsg_link_out8_d2_i
  ,input  p_bsg_link_out8_d3_i
  ,input  p_bsg_link_out8_d4_i
  ,input  p_bsg_link_out8_d5_i
  ,input  p_bsg_link_out8_d6_i
  ,input  p_bsg_link_out8_d7_i
  ,input  p_bsg_link_out8_d8_i
  
  ,input  p_bsg_link_out9_clk_i
  ,input  p_bsg_link_out9_v_i
  ,output p_bsg_link_out9_tkn_o
  ,input  p_bsg_link_out9_d0_i
  ,input  p_bsg_link_out9_d1_i
  ,input  p_bsg_link_out9_d2_i
  ,input  p_bsg_link_out9_d3_i
  ,input  p_bsg_link_out9_d4_i
  ,input  p_bsg_link_out9_d5_i
  ,input  p_bsg_link_out9_d6_i
  ,input  p_bsg_link_out9_d7_i
  ,input  p_bsg_link_out9_d8_i

  ,input  p_bsg_link_out10_clk_i
  ,input  p_bsg_link_out10_v_i
  ,output p_bsg_link_out10_tkn_o
  ,input  p_bsg_link_out10_d0_i
  ,input  p_bsg_link_out10_d1_i
  ,input  p_bsg_link_out10_d2_i
  ,input  p_bsg_link_out10_d3_i
  ,input  p_bsg_link_out10_d4_i
  ,input  p_bsg_link_out10_d5_i
  ,input  p_bsg_link_out10_d6_i
  ,input  p_bsg_link_out10_d7_i
  ,input  p_bsg_link_out10_d8_i
  
  ,input  p_bsg_link_out11_clk_i
  ,input  p_bsg_link_out11_v_i
  ,output p_bsg_link_out11_tkn_o
  ,input  p_bsg_link_out11_d0_i
  ,input  p_bsg_link_out11_d1_i
  ,input  p_bsg_link_out11_d2_i
  ,input  p_bsg_link_out11_d3_i
  ,input  p_bsg_link_out11_d4_i
  ,input  p_bsg_link_out11_d5_i
  ,input  p_bsg_link_out11_d6_i
  ,input  p_bsg_link_out11_d7_i
  ,input  p_bsg_link_out11_d8_i
  
  ,input  p_bsg_link_out12_clk_i
  ,input  p_bsg_link_out12_v_i
  ,output p_bsg_link_out12_tkn_o
  ,input  p_bsg_link_out12_d0_i
  ,input  p_bsg_link_out12_d1_i
  ,input  p_bsg_link_out12_d2_i
  ,input  p_bsg_link_out12_d3_i
  ,input  p_bsg_link_out12_d4_i
  ,input  p_bsg_link_out12_d5_i
  ,input  p_bsg_link_out12_d6_i
  ,input  p_bsg_link_out12_d7_i
  ,input  p_bsg_link_out12_d8_i
  
  ,input  p_bsg_link_out13_clk_i
  ,input  p_bsg_link_out13_v_i
  ,output p_bsg_link_out13_tkn_o
  ,input  p_bsg_link_out13_d0_i
  ,input  p_bsg_link_out13_d1_i
  ,input  p_bsg_link_out13_d2_i
  ,input  p_bsg_link_out13_d3_i
  ,input  p_bsg_link_out13_d4_i
  ,input  p_bsg_link_out13_d5_i
  ,input  p_bsg_link_out13_d6_i
  ,input  p_bsg_link_out13_d7_i
  ,input  p_bsg_link_out13_d8_i
  
  ,input  p_bsg_link_out14_clk_i
  ,input  p_bsg_link_out14_v_i
  ,output p_bsg_link_out14_tkn_o
  ,input  p_bsg_link_out14_d0_i
  ,input  p_bsg_link_out14_d1_i
  ,input  p_bsg_link_out14_d2_i
  ,input  p_bsg_link_out14_d3_i
  ,input  p_bsg_link_out14_d4_i
  ,input  p_bsg_link_out14_d5_i
  ,input  p_bsg_link_out14_d6_i
  ,input  p_bsg_link_out14_d7_i
  ,input  p_bsg_link_out14_d8_i
  
  ,input  p_bsg_link_out15_clk_i
  ,input  p_bsg_link_out15_v_i
  ,output p_bsg_link_out15_tkn_o
  ,input  p_bsg_link_out15_d0_i
  ,input  p_bsg_link_out15_d1_i
  ,input  p_bsg_link_out15_d2_i
  ,input  p_bsg_link_out15_d3_i
  ,input  p_bsg_link_out15_d4_i
  ,input  p_bsg_link_out15_d5_i
  ,input  p_bsg_link_out15_d6_i
  ,input  p_bsg_link_out15_d7_i
  ,input  p_bsg_link_out15_d8_i
  
  ,input  p_bsg_link_out16_clk_i
  ,input  p_bsg_link_out16_v_i
  ,output p_bsg_link_out16_tkn_o
  ,input  p_bsg_link_out16_d0_i
  ,input  p_bsg_link_out16_d1_i
  ,input  p_bsg_link_out16_d2_i
  ,input  p_bsg_link_out16_d3_i
  ,input  p_bsg_link_out16_d4_i
  ,input  p_bsg_link_out16_d5_i
  ,input  p_bsg_link_out16_d6_i
  ,input  p_bsg_link_out16_d7_i
  ,input  p_bsg_link_out16_d8_i
  
  ,input  p_bsg_link_out17_clk_i
  ,input  p_bsg_link_out17_v_i
  ,output p_bsg_link_out17_tkn_o
  ,input  p_bsg_link_out17_d0_i
  ,input  p_bsg_link_out17_d1_i
  ,input  p_bsg_link_out17_d2_i
  ,input  p_bsg_link_out17_d3_i
  ,input  p_bsg_link_out17_d4_i
  ,input  p_bsg_link_out17_d5_i
  ,input  p_bsg_link_out17_d6_i
  ,input  p_bsg_link_out17_d7_i
  ,input  p_bsg_link_out17_d8_i
  
  ,input  p_bsg_link_out18_clk_i
  ,input  p_bsg_link_out18_v_i
  ,output p_bsg_link_out18_tkn_o
  ,input  p_bsg_link_out18_d0_i
  ,input  p_bsg_link_out18_d1_i
  ,input  p_bsg_link_out18_d2_i
  ,input  p_bsg_link_out18_d3_i
  ,input  p_bsg_link_out18_d4_i
  ,input  p_bsg_link_out18_d5_i
  ,input  p_bsg_link_out18_d6_i
  ,input  p_bsg_link_out18_d7_i
  ,input  p_bsg_link_out18_d8_i
  
  ,input  p_bsg_link_out19_clk_i
  ,input  p_bsg_link_out19_v_i
  ,output p_bsg_link_out19_tkn_o
  ,input  p_bsg_link_out19_d0_i
  ,input  p_bsg_link_out19_d1_i
  ,input  p_bsg_link_out19_d2_i
  ,input  p_bsg_link_out19_d3_i
  ,input  p_bsg_link_out19_d4_i
  ,input  p_bsg_link_out19_d5_i
  ,input  p_bsg_link_out19_d6_i
  ,input  p_bsg_link_out19_d7_i
  ,input  p_bsg_link_out19_d8_i

  // bsg tag interface, 5 pins
  ,output p_bsg_tag_clk_o
  ,output p_bsg_tag_en_o
  ,output p_bsg_tag_data_o
  ,input  p_bsg_tag_clk_i
  ,input  p_bsg_tag_data_i
  // clock and reset interface, 9 pins
  // clock input signals
  ,output p_clk_A_o
  ,output p_clk_B_o
  ,output p_clk_C_o
  // clock output signal
  ,input  p_clk_i
  // 3-bit clock selection signals
  ,output p_sel_0_o
  ,output p_sel_1_o
  ,output p_sel_2_o
  // asynchronous reset signals
  ,output p_clk_async_reset_o
  ,output p_core_async_reset_o
  // miscellaneous signal, 1 pin
  ,input  p_misc_i
  );
// End HB BGA PAD Definitions
// **********************************************************************
