config bsg_config;
  design `BSG_DESIGNS_TESTING_LIBRARY_NAME.`BSG_TOP_SIM_MODULE;
  default liblist `BSG_DESIGNS_TESTING_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME work;
  instance `BSG_CHIP_INSTANCE_PATH liblist `BSG_CHIP_LIBRARY_NAME;

  // each ip block with its library
  instance `BSG_TILE_SUBARRAY_PATH_0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // In order to harden some tiles, but not all, we need to specify each tile we want to be synthesized.
  // There may be a better way to do this, but I don't know it
  instance `BSG_TILE_NETLIST_PATH_X0Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X1Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X2Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X3Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X4Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X5Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X6Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X7Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X8Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X9Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X10Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X11Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X12Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X13Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X14Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X15Y0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X0Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X1Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X2Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X3Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X4Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X5Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X6Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X7Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X8Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X9Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X10Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X11Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X12Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X13Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X14Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X15Y1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_SUBARRAY_PATH_1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X0Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X1Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X2Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X3Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X4Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X5Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X6Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X7Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X8Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X9Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X10Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X11Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X12Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X13Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X14Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X15Y2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X0Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X1Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X2Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X3Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X4Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X5Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X6Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X7Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X8Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X9Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X10Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X11Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_TILE_NETLIST_PATH_X12Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X13Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X14Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_TILE_NETLIST_PATH_X15Y3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_CACHE_SUBARRAY_PATH liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_NORTH_CACHE_NETLIST_PATH_X0 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X1 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X2 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X3 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_NORTH_CACHE_NETLIST_PATH_X4 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X5 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X6 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X7 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_NORTH_CACHE_NETLIST_PATH_X8 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X9 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X10 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X11 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  instance `BSG_NORTH_CACHE_NETLIST_PATH_X12 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X13 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X14 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  instance `BSG_NORTH_CACHE_NETLIST_PATH_X15 liblist `BSG_MANYCORE_TILE_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_manycore_tile_compute_ruche liblist `BSG_MANYCORE_TILE_HARD_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_tile_vcache liblist `BSG_MANYCORE_TILE_HARD_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bigblade_clk_gen liblist `BIGBLADE_CLK_GEN_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_chip_io_link_ddr liblist `BIGBLADE_IO_LINK_DDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_chip_noc_io_link liblist `BIGBLADE_NOC_IO_LINK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_chip_noc_mem_link liblist `BIGBLADE_NOC_MEM_LINK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // cell bsg_manycore_pod_row_sdr liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_manycore_link_ruche_to_sdr_east liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_link_ruche_to_sdr_west liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_manycore_link_to_sdr_north liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_link_to_sdr_north_row liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_manycore_link_to_sdr_south liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_link_to_sdr_south_row liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_manycore_link_wh_to_sdr_ne liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_link_wh_to_sdr_nw liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_link_wh_to_sdr_se liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_manycore_link_wh_to_sdr_sw liblist `BSG_MANYCORE_LINK_SDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  // bsg tie hi/lo
  cell bsg_tiehi liblist `BSG_TIEHILO_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_tielo liblist `BSG_TIEHILO_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

endconfig
