config bsg_config;
  design `BSG_DESIGNS_TESTING_LIBRARY_NAME.`BSG_TOP_SIM_MODULE;
  default liblist `BSG_DESIGNS_TESTING_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME work;

  // Swaplist is a list of instances to swap for ***netlists***. In this TB
  // it swaps out quadrapod 0, and enumerates the top qudrapod
  // (bsg_manycore_pod_row_sdr), all 16x2 tile arrays within the pods,
  // all tiles within the tile arrays, all north and south cache
  // arrays within the pods, and all caches within the cache arrays.

  // Swaplist.vh is generated by the makefile.
  `include "swaplist.vh"

  // Swap these for netlists, universally.
  cell bigblade_clk_gen liblist `BIGBLADE_CLK_GEN_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_chip_io_link_ddr liblist `BIGBLADE_IO_LINK_DDR_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_chip_noc_io_link liblist `BIGBLADE_NOC_IO_LINK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_chip_noc_mem_link liblist `BIGBLADE_NOC_MEM_LINK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_tiehi liblist `BSG_TIEHILO_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;
  cell bsg_tielo liblist `BSG_TIEHILO_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;

  cell bsg_chip_block liblist `BIGBLADE_TOPLEVEL_BLOCK_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;  
  cell bsg_chip liblist `BIGBLADE_TOPLEVEL_LIBRARY_NAME `BSG_CHIP_LIBRARY_NAME;  

  // else RTL
endconfig
